# Generated by Django 5.2.13 on 2026-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('action_type', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('subject_id', 'action_type', 'target_date')},
            },
        ),
    ]
