# Generated by Django 5.2 on 2026-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('finance_head', 'Finance Head'), ('issuer', 'Issuer'), ('viewer', 'Viewer')], default='issuer', max_length=20),
        ),
    ]
