# Generated by Django 5.2 on 2026-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ams_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('finance_head', 'Finance Head'), ('finance_executive', 'Finance Executive'), ('manager', 'Manager'), ('employee', 'Employee'), ('viewer', 'Viewer')], default='finance_executive', max_length=20),
        ),
    ]
