# Generated by Django 5.2 on 2026-04-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('accounts', '0004_remove_it_role'),
    ]

    operations = [
    ]
