# Generated by Django 5.2 on 2026-04-16 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.SlugField(unique=True)),
                ('registered_address', models.TextField(help_text='Full registered address as it appears on letters.')),
                ('cin', models.CharField(help_text='Corporate Identification Number', max_length=21, verbose_name='CIN')),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('signatory_name', models.CharField(max_length=200)),
                ('signatory_designation', models.CharField(help_text='e.g. "Director, HR"', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='Job role / function', max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('salary_current', models.DecimalField(blank=True, decimal_places=2, help_text='Current monthly gross salary (INR). Used as default in salary letters.', max_digits=12, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('hris', 'HRIS Sync')], default='manual', max_length=10)),
                ('source_system_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='documents.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('salary_letter', 'Salary Letter'), ('noc', 'No Objection Certificate'), ('experience_certificate', 'Experience Certificate')], max_length=50)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('html_content', models.TextField(help_text='Django template syntax. Variables: {{ company }}, {{ employee }}, {{ issue_date }}, etc.')),
                ('extra_variables_schema', models.JSONField(default=dict, help_text='JSON schema for template-specific form fields. See TEMPLATE_EXTRA_SCHEMAS in models.py.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one version per template name can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Template',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variables_snapshot', models.JSONField()),
                ('s3_key', models.CharField(max_length=500)),
                ('content_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('void', 'Void')], default='generated', max_length=20)),
                ('download_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.company')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.lettertemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('document.generated', 'Document Generated'), ('document.downloaded', 'Document Downloaded'), ('document.voided', 'Document Voided'), ('document.generation_failed', 'Document Generation Failed'), ('template.published', 'Template Published'), ('user.role_changed', 'User Role Changed'), ('audit.flag.template_issuer_overlap', 'Template-Issuer Overlap Flag'), ('reconciliation.mismatch', 'Reconciliation Mismatch'), ('reconciliation.ok', 'Reconciliation OK')], db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='documents_a_event_t_c7d193_idx')],
            },
        ),
    ]
