# Generated by Django 5.2 on 2026-04-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('document.generated', 'Document Generated'), ('document.downloaded', 'Document Downloaded'), ('document.voided', 'Document Voided'), ('document.viewed', 'Document Viewed'), ('document.access_denied', 'Document Access Denied'), ('document.locked', 'Document Locked'), ('document.unlocked', 'Document Unlocked'), ('document.generation_failed', 'Document Generation Failed'), ('template.published', 'Template Published'), ('user.role_changed', 'User Role Changed'), ('audit.flag.template_issuer_overlap', 'Template-Issuer Overlap Flag'), ('reconciliation.mismatch', 'Reconciliation Mismatch'), ('reconciliation.ok', 'Reconciliation OK')], db_index=True, max_length=100),
        ),
    ]
