# Generated by Django 5.2 on 2026-04-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
