# Generated by Django 5.2 on 2026-04-22 07:56

import documents.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_contractlensrecord_auditevent_cl_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlensrecord',
            name='contract_data',
            field=documents.fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contractlensrecord',
            name='source_files_meta',
            field=documents.fields.EncryptedJSONField(default=list),
        ),
    ]
