# Generated by Django 5.2.13 on 2026-04-20 16:08

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('subscription', 'Subscription'), ('misc_expense', 'Misc Expense')], max_length=20)),
                ('state', django_fsm.FSMField(default='pending_manager', max_length=50, protected=True)),
                ('service_name', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-Time')], max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('expense_type', models.CharField(blank=True, choices=[('one_off', 'One-Off'), ('recurring', 'Recurring')], max_length=20)),
                ('amount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('vendor_account_id', models.CharField(blank=True, max_length=200)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('finance_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
