# Generated by Django 5.2 on 2026-04-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams_approvals', '0003_merge_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='assigned_finance',
        ),
    ]
